// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVMJdgiecqdqG7ESPqWEjcEz4gEz1gbA',
    appId: '1:813025681886:web:04e973e07d01ef3a267d4f',
    messagingSenderId: '813025681886',
    projectId: 'geargo-e0035',
    authDomain: 'geargo-e0035.firebaseapp.com',
    storageBucket: 'geargo-e0035.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72StYLf5ECEmohXZda84IqOREoWS6F6I',
    appId: '1:813025681886:android:9990a176c39fb6db267d4f',
    messagingSenderId: '813025681886',
    projectId: 'geargo-e0035',
    storageBucket: 'geargo-e0035.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBVMJdgiecqdqG7ESPqWEjcEz4gEz1gbA',
    appId: '1:813025681886:web:c2a7f8a2e5ac68e1267d4f',
    messagingSenderId: '813025681886',
    projectId: 'geargo-e0035',
    authDomain: 'geargo-e0035.firebaseapp.com',
    storageBucket: 'geargo-e0035.firebasestorage.app',
  );
}
